FRIEND_REQUEST_PENDING = 1
FRIEND_REQUEST_ACCEPTED = 2
FRIEND_REQUEST_REJECTED = 3

FRIEND_REQUEST_STATUS_UPSERT_LIST = [
    FRIEND_REQUEST_PENDING,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_REJECTED
]